### PR TITLE
Fix context inheritance and optionally add context to global loggers

### LINKED ISSUE #185: CorrelationId not set when creating Child Logger
Hi,

I discovered, that creating a new Child Logger doesn't work with the new version as before (v6).
Before I used the `createLogger()` function to create a new logger and got automatically the `correlation_id` property set ([code](https://github.com/SAP/cf-nodejs-logging-support/blob/c16436a1b252066d5c223895694fb3502c01683b/core/log-core.js#L620).

When doing the same with the current version of the library, the `correlation_id` is not set. Even calling the `setCorrelationId()` method of the logger doesn't work :(

### PR DESCRIPTION
**Pull request by christiand93**
Changes
* Fix context inheritance
   * Child loggers inherit context fields (e.g., correlation_id) from their parent logger, if present.
* Add context to global child loggers
   * Child loggers derived from the global logger _optionally_ support context features now. This includes
     * support for `setContextProperty()`, `setCorrelationId()`, `setTenantId()`, `setTenantSubdomain()` and the respective _get_ methods.
     * auto-generated correlation_id (default configuration)
     * context inheritance
   * A new child logger can be equipped with a **new** context by specifying `true` for the `createNewContext` parameter:
 
     ```js
     const logger = log.createLogger(null, true)
     ```
* Add a boolean return value for `setContextProperty()`, `setCorrelationId()`, `setTenantId()` and `setTenantSubdomain()` to indicate if the _set_ operation was successful. If a logger does not have a context, the fields cannot be set and the methods return `false`. 
* Add test cases for context inheritance
* Add/update documentation on contexts and child loggers

Fixes #185

### CODE REVIEW

File: src/lib/logger/logger.ts [hunk 1]
```diff
@@ -3,39 +3,42 @@ import { isValidObject } from '../middleware/utils';
...
         if (customFields) {
             logger.setCustomFields(customFields);
         }
         return logger;
     }
 
+    createContext() {
+        this.context = new Context();
+    }
+
```
Comment (christiand93) [inline src/lib/logger/logger.ts:41]: Call w/ @nicklas-dohrn:
- use flag in createLogger instead, e.g.,  createNewContext
- return bool when setting a context property to indicate success

**Review by nicklas-dohrn — APPROVED** [review]
LGTM
